### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [maocypher/dogsportsdiary#77]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8455404280

Could you please clean the cache and rebuild the apk? Thanks!

**Comment by maocypher** [comment]
@linsui how do I clean the cache and which cache?
The last run was successful: [https://gitlab.com/maocypher/fdroiddata/-/pipelines/1557959255](https://gitlab.com/maocypher/fdroiddata/-/pipelines/1557959255)

**Comment by linsui** [comment]
Hmmm, did you changed the tag? We built the apk against fec2cf4faa067efce8d7057311e1d2e951f8b61f.

**Comment by maocypher** [comment]
I created a tag to test it locally. I was flagged as prerelease

**Comment by maocypher** [comment]
Is closed, because the build was successful. The tag was recreated

**Comment by linsui** [comment]
Thanks!
